/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'B' }],
  test: [{
    type: 'autogenerated',
    dirName: 'A',
  },],
  learn_shell: [
    {
      type: 'autogenerated',
      dirName: 'learn_shell', // '.' means the current docs folder
    },
  ],


};

export default sidebars;
